server:
  port: 8181

spring:
  datasource:
    username: joxa
    password: 1234
    url: jdbc:oracle:thin:@192.168.0.113:1521/xe
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB

upload:
  server:
    folder: /Users/macbookpro/Desktop/filesUpload


